### ISSUE TITLE
Detect other kinds of errorf wrapping

### ISSUE THREAD

**Issue by coder543** [polyfloyd/go-errorlint#2]
One antipattern I was hoping this linter would catch, but it didn't:

```fmt.Errorf("oh no: %s", err.Error())```

Would it be practical to detect this as well?

Unrelated question, but have you tried submitting this for inclusion in `golangci-lint`? Your linter seems really useful!

**Comment by polyfloyd** [comment]
Yes, that does seem useful and is probably not too hard to add.

golangci-lint support is tracked here: https://github.com/golangci/golangci-lint/issues/1030 It's currently up to me to update the linter to the system they use
